require('dotenv').config();
const { GoogleGenerativeAI } = require('@google/generative-ai');
const logger = require('../utils/logger');

let _genAI = null;
function getGenAI() {
  if (!_genAI) _genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  return _genAI;
}

const SYSTEM_PROMPT = `You are a Senior Quantitative Risk Manager and the 'Ultimate Judge' for an autonomous trading system.
Your role: Review trade theses generated by a secondary AI (Ollama) and decide whether to APPROVE or REJECT them based on risk, technicals, and sentiment.
Be extremely selective. Only 'LONG' or 'SHORT' if the data is compelling.`;

/**
 * Verifies a batch of symbols analyzed by Ollama.
 * @param {Array<{ symbol: string, bundle: object, ollamaResult: object }>} batch 
 */
async function verifyBatch(batch) {
  const model = getGenAI().getGenerativeModel({
    model: process.env.GEMINI_MODEL || 'gemini-1.5-flash',
    generationConfig: { responseMimeType: 'application/json' },
  });

  const prompt = `
As the Ultimate Judge, review these ${batch.length} potential trade opportunities.
Each trade was initially analyzed by a local instance of Llama-3.

DATA BATCH:
${batch.map((item, i) => `
--- ITEM ${i + 1}: ${item.symbol} ---
PRICE: ${item.bundle.price} (${item.bundle.trend})
OLLAMA SENTIMENT: ${item.ollamaResult?.sentiment}
OLLAMA SUMMARY: ${item.ollamaResult?.summary}
INDICATORS: RSI=${item.bundle.rsi14}, EMA9=${item.bundle.ema9}, EMA21=${item.bundle.ema21}
NEWS SUMMARY: ${item.bundle.headlines.slice(0, 3).map(h => h.title).join(' | ')}
`).join('\n')}

For each symbol, return a decision. 
Return ONLY this JSON structure:
{
  "results": [
    {
      "symbol": "<symbol>",
      "approved": <true|false>,
      "direction": <"LONG" | "SHORT" | "NO_TRADE">,
      "score": <integer -100 to 100>,
      "reason": "<short justification>",
      "refinement_feedback": "<if approved=false, provide 1 sentence on what Ollama missed or should re-check>"
    },
    ...
  ]
}`;

  try {
    const result = await model.generateContent(prompt);
    const text = result.response.text().trim();
    const parsed = JSON.parse(text);

    logger.info('Batch Gemini verification complete', { 
      total: batch.length, 
      approved: parsed.results.filter(r => r.approved).length 
    });

    return parsed.results;
  } catch (err) {
    logger.error('Batch Gemini verification failed', { error: err.message });
    return batch.map(item => ({
      symbol: item.symbol,
      approved: false,
      score: 0,
      reason: 'Gemini verification failed',
      refinement_feedback: err.message
    }));
  }
}

async function analyze(bundle) {
  // Keeping old analyze for backward compatibility/individual runs
  const model = getGenAI().getGenerativeModel({
    model: process.env.GEMINI_MODEL || 'gemini-2.0-flash',
    generationConfig: { responseMimeType: 'application/json' },
  });

  const prompt = `
Analyze this market data for ${bundle.symbol} and return a JSON trade thesis.

MARKET DATA:
- Current Price:   ${bundle.price} ${bundle.changePct >= 0 ? '+' : ''}${bundle.changePct?.toFixed(2)}%
- EMA 9:           ${bundle.ema9 ?? 'N/A'}
- EMA 21:          ${bundle.ema21 ?? 'N/A'}
- RSI 14:          ${bundle.rsi14 ?? 'N/A'}
- Trend:           ${bundle.trend}
- Regime:          ${bundle.regime}
- Volume Trend:    ${bundle.volumeTrend}

RELEVANT HEADLINES:
${bundle.headlines.slice(0, 5).map(h => `- ${h.title}`).join('\n')}

Return ONLY JSON:
{
  "score": <-100 to 100>,
  "direction": <"LONG"|"SHORT"|"NO_TRADE">,
  "confidence": <0-100>,
  "thesis": <string>,
  "key_risk": <string>
}`;

  try {
    const result = await model.generateContent(prompt);
    const text = result.response.text().trim();
    return JSON.parse(text);
  } catch (err) {
    logger.error('Gemini analyze failed', { symbol: bundle.symbol, error: err.message });
    return null;
  }
}

module.exports = { analyze, verifyBatch };
