require('dotenv').config();
const { GoogleGenerativeAI } = require('@google/generative-ai');
const logger = require('../utils/logger');

let _genAI = null;
function getGenAI() {
  if (!_genAI) _genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  return _genAI;
}

const GEMINI_MODEL_CANDIDATES = Array.from(new Set([
  process.env.GEMINI_MODEL,
  'gemini-2.0-flash',
  'gemini-1.5-flash',
  'gemini-1.5',
  'gemini-1.0'
].filter(Boolean)));

async function generateWithGemini(prompt) {
  let lastError = null;
  for (const modelName of GEMINI_MODEL_CANDIDATES) {
    try {
      const model = getGenAI().getGenerativeModel({
        model: modelName,
        generationConfig: { responseMimeType: 'application/json' },
      });
      return await model.generateContent(prompt);
    } catch (err) {
      lastError = err;
      logger.warn('Gemini model attempt failed', { model: modelName, error: err.message });
      const message = (err.message || '').toLowerCase();
      if (!/not found|unsupported|unregistered callers|quota|rate limited|403|404|invalid model/.test(message)) {
        break;
      }
    }
  }
  throw lastError;
}

const SYSTEM_PROMPT = `You are a Senior Quantitative Risk Manager and the 'Ultimate Judge' for an autonomous trading system.
Your role: Review trade theses generated by a secondary AI (Ollama) and decide whether to APPROVE or REJECT them based on risk, technicals, and sentiment.
Be extremely selective. Only 'LONG' or 'SHORT' if the data is compelling.`;

/**
 * Verifies a batch of symbols analyzed by Ollama.
 * @param {Array<{ symbol: string, bundle: object, ollamaResult: object }>} batch 
 */
async function verifyBatch(batch) {
  const prompt = `
As the Ultimate Judge, review these ${batch.length} potential trade opportunities.
Each trade was initially analyzed by a local instance of Llama-3.

DATA BATCH:
${batch.map((item, i) => `
ITEM ${i + 1}: ${item.symbol} | PRICE: ${item.bundle.price} (${item.bundle.trend})
OLLAMA SENTIMENT: ${item.ollamaResult?.sentiment} | SUMMARY: ${item.ollamaResult?.summary}
INDICATORS: RSI=${item.bundle.rsi14}, EMA9=${item.bundle.ema9}/${item.bundle.ema21}
TOP NEWS: ${item.bundle.headlines[0]?.title || 'None'}
`).join('\n')}

For each symbol, return a decision. 
If 'approved' is false but technicals and sentiment look close, provide 'refinement_feedback' (1 sentence) for Ollama to re-check.
Return ONLY this JSON structure:
{
  "results": [
    {
      "symbol": "<symbol>",
      "approved": <true|false>,
      "direction": <"LONG" | "SHORT" | "NO_TRADE">,
      "score": <integer -100 to 100>,
      "reason": "<short justification>",
      "refinement_feedback": "<optional - what should Ollama re-investigate?>"
    },
    ...
  ]
}`;

  try {
    const result = await generateWithGemini(prompt);
    const text = result.response.text().trim();
    const parsed = JSON.parse(text);

    logger.info('Batch Gemini verification complete', { 
      total: batch.length, 
      approved: parsed.results.filter(r => r.approved).length 
    });

    return parsed.results;
  } catch (err) {
    logger.error('Batch Gemini verification failed', { error: err.message });
    return batch.map(item => ({
      symbol: item.symbol,
      approved: false,
      score: 0,
      reason: 'Gemini verification failed',
      refinement_feedback: err.message
    }));
  }
}

async function analyze(bundle) {
  // Keeping old analyze for backward compatibility/individual runs

  const prompt = `
Analyze this market data for ${bundle.symbol} and return a JSON trade thesis.

MARKET DATA:
- Current Price:   ${bundle.price} ${bundle.changePct >= 0 ? '+' : ''}${bundle.changePct?.toFixed(2)}%
- EMA 9:           ${bundle.ema9 ?? 'N/A'}
- EMA 21:          ${bundle.ema21 ?? 'N/A'}
- RSI 14:          ${bundle.rsi14 ?? 'N/A'}
- Trend:           ${bundle.trend}
- Regime:          ${bundle.regime}
- Volume Trend:    ${bundle.volumeTrend}

RELEVANT HEADLINES:
${bundle.headlines.slice(0, 5).map(h => `- ${h.title}`).join('\n')}

Return ONLY JSON:
{
  "score": <-100 to 100>,
  "direction": <"LONG"|"SHORT"|"NO_TRADE">,
  "confidence": <0-100>,
  "thesis": <string>,
  "key_risk": <string>
}`;

  try {
    const result = await generateWithGemini(prompt);
    const text = result.response.text().trim();
    return JSON.parse(text);
  } catch (err) {
    logger.error('Gemini analyze failed', { symbol: bundle.symbol, error: err.message });
    return null;
  }
}

module.exports = { analyze, verifyBatch };
